server:
  port: 8082

spring:
  application:
    name: thesis-service

  datasource:
    url: jdbc:sqlserver://103.157.204.54:1433;databaseName=thesis_db;encrypt=false
    #    username: ${DB_USERNAME}
    #    password: ${DB_PASSWORD}
    username: sa
    password: hai@123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServer2012Dialect

  cloud:
    discovery:
      enabled: true

  devtools:
    livereload:
      enabled: false

eureka:
  instance:
    prefer-ip-address: false
    hostname: ${RAILWAY_PUBLIC_DOMAIN:thesis-service-production.up.railway.app}
    instance-id: ${spring.application.name}:${random.value}
    non-secure-port: 8082

  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true

jwt:
  secret: VHJlbmRvaW5heW5ndW9pZGFuZ2RldHJhbnRyb25nbmFodGFsYW5ndW9pZGFzYW5zYW5nYm90aG9pZ2lhbmRlY2hhbXNvY2JhblRob2lnaWFuY3VhYWljdW5nZGV1ZGFuZ3F1eW5odW5oYWVkZW10aG9pZ2lhbmN1YW5ndW95ZGFuaGNob2JhbmNvbmdnaW9uZ2h1dmllY2RlbWNhdGhlZ2lvaWN1YWJhbnRoYW5jaGlhc2VjdW5nYmFu
  expiration: 86400000
  refresh-expiration: 604800000

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
