server:
  port: ${PORT:8090} # Railway cấp port runtime, mặc định 8090 nếu chạy local

spring:
  application:
    name: auth-service

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  cloud:
    discovery:
      enabled: true

  devtools:
    livereload:
      enabled: false

eureka:
  instance:
    prefer-ip-address: false
    hostname: ${RAILWAY_PUBLIC_DOMAIN:auth-service-production-c217.up.railway.app} # hostname public do Railway cấp
    instance-id: ${spring.application.name}:${random.value}
    non-secure-port: ${PORT} # port runtime thực tế

  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true

jwt:
  secret: VHJlbmRvaW5heW5ndW9pZGFuZ2RldHJyb25nbmFodGFsYW5ndW9pZGFzYW5zYW5nYm90aG9pZ2lhbmRlY2hhbXNvY2JhblRob2lnaWFuY3VhYWljdW5nZGV1ZGFuZ3F1eW5odW5oYWVkZW10aG9pZ2lhbmN1YW5ndW95ZGFuaGNob2JhbmNvbmdnaW9uZ2h1dmllY2RlbWNhdGhlZ2lvaWN1YWJhbnRoYW5jaGlhc2VjdW5nYmFu
  expiration: 86400000
  refresh-expiration: 604800000

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
