server:
  port: 8081
  # Tăng timeout để xử lý import lớn
  tomcat:
    connection-timeout: 300000 # 5 phút
    max-connections: 8192
    accept-count: 100
    max-threads: 200
  servlet:
    session:
      timeout: 30m # 30 phút
  # Cấu hình async request timeout
  async:
    request-timeout: 900000 # 15 phút cho import operations
    thread-pool:
      core-size: 20
      max-size: 100
      queue-capacity: 200

spring:
  application:
    name: user-service

  datasource:
#    url: jdbc:sqlserver://103.157.204.54:1433;databaseName=user_db;encrypt=false
#    username: sa
#    password: hai@123
    url: jdbc:sqlserver://localhost:1433;databaseName=user_db;encrypt=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    # Database timeout configuration
    hikari:
      connection-timeout: 300000 # 5 phút
      idle-timeout: 600000 # 10 phút
      max-lifetime: 1800000 # 30 phút
      maximum-pool-size: 20
      minimum-idle: 5
      connection-test-query: SELECT 1

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        # JPA timeout configuration
        jdbc:
          batch_size: 10 # Giảm batch size để tránh rollback issues
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
        # Transaction configuration
        transaction:
          factory_class: org.hibernate.transaction.JDBCTransactionFactory
        connection:
          provider_disables_autocommit: true

  cloud:
    discovery:
      enabled: true

  devtools:
    livereload:
      enabled: false

eureka:
  instance:
    prefer-ip-address: false
    hostname: ${RAILWAY_PUBLIC_DOMAIN:user-service-production-495b.up.railway.app}
    instance-id: ${spring.application.name}:${random.value}
    non-secure-port: 8081

  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true

jwt:
  secret: VHJlbmRvaW5heW5ndW9pZGFuZ2RldHJhbnRyb25nbmFodGFsYW5ndW9pZGFzYW5zYW5nYm90aG9pZ2lhbmRlY2hhbXNvY2JhblRob2lnaWFuY3VhYWljdW5nZGV1ZGFuZ3F1eW5odW5oYWVkZW10aG9pZ2lhbmN1YW5ndW95ZGFuaGNob2JhbmNvbmdnaW9uZ2h1dmllY2RlbWNhdGhlZ2lvaWN1YWJhbnRoYW5jaGlhc2VjdW5nYmFu
  expiration: 86400000
  refresh-expiration: 604800000

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.security: DEBUG
